---
- name: Add third party repository
  apt_repository: repo="ppa:fkrull/deadsnakes" state=present

- name : Run apt-get update
  apt: update_cache=yes

- name: Install libs
  apt: name={{item}} state=latest
  with_items:
    - python3.6
    - python3.6-dev

- name: remove python3 link
  file: src=/usr/bin/python3.6 dest=/usr/bin/python3 state=link force=yes

- name : Install pip
  apt : name=python3-pip state=present
